"""File generator functions for the Alcatraz Setup Wizard."""

import sys
import json
import textwrap
from pathlib import Path

from shared import console, VERSION, Progress, SpinnerColumn, TextColumn, BarColumn
from config import SetupConfig


def generate_git_guardian(config: SetupConfig) -> str:
    # Quote each branch name to prevent glob interpretation in bash case statements.
    # Single quotes disable wildcards in case patterns. The branch regex guarantees
    # no single quotes in names, so this is safe.
    branches = "|".join(f"'{b}'" for b in config.protected_branches)

    # Build the push case
    push_extra = ""
    if config.guardian_auto_allow_claude_branches and not config.guardian_confirm_all_pushes:
        push_extra = """
        elif args_match '^claude/' "${sub_args[@]}"; then
            echo -e "${GREEN}● Git Guardian: push to claude/ branch allowed${NC}" >&2
            log "PASSED: claude/ branch push"
"""

    push_else = ""
    if config.guardian_confirm_all_pushes:
        push_else = """        else
            confirm "MEDIUM" "Push detected. Confirm to proceed." "$@" || exit 1"""
    else:
        push_else = """        else
            echo -e "${GREEN}● Git Guardian: push allowed (feature branch)${NC}" >&2
            log "PASSED: feature branch push"
"""

    return textwrap.dedent(f'''\
#!/bin/bash
# git-guardian.sh — intercepts dangerous git commands and asks for confirmation
# Generated by Alcatraz Setup Wizard v{VERSION}

REAL_GIT="/usr/bin/git"

# ─── Logging ───
LOG_FILE="/tmp/git-guardian.log"
log() {{
    echo "$(date '+%Y-%m-%d %H:%M:%S') | $*" >> "$LOG_FILE"
}}
log "COMMAND: git $*"

# ─── Colour codes ───
RED='\\033[0;31m'
YELLOW='\\033[1;33m'
GREEN='\\033[0;32m'
CYAN='\\033[0;36m'
BOLD='\\033[1m'
NC='\\033[0m'

# ─── Helper: check if any argument matches a pattern ───
args_match() {{
    local pattern="$1"
    shift
    for arg in "$@"; do
        if [[ "$arg" =~ $pattern ]]; then
            return 0
        fi
    done
    return 1
}}

# ─── Helper: check if a specific branch name appears in args ───
has_protected_branch() {{
    for arg in "$@"; do
        [[ "$arg" == -* ]] && continue
        case "$arg" in
            {branches}) return 0 ;;
        esac
    done
    return 1
}}

# ─── Helper: ask the user ───
confirm() {{
    local risk_level="$1"
    local description="$2"
    local colour="$YELLOW"
    [[ "$risk_level" == "HIGH" ]] && colour="$RED"

    local label="GIT GUARDIAN — ${{risk_level}} RISK ACTION DETECTED"
    local width=56

    echo "" >&2
    printf "${{colour}}╔%${{width}}s╗${{NC}}\\n" "" | tr ' ' '═' >&2
    printf "${{colour}}║${{NC}}  %-$(( width - 2 ))s${{colour}}║${{NC}}\\n" "$label" >&2
    printf "${{colour}}╠%${{width}}s╣${{NC}}\\n" "" | tr ' ' '═' >&2
    printf "${{colour}}║${{NC}}  %-$(( width - 2 ))s${{colour}}║${{NC}}\\n" "$description" >&2
    printf "${{colour}}║${{NC}}  %-$(( width - 2 ))s${{colour}}║${{NC}}\\n" "" >&2
    printf "${{colour}}║${{NC}}  %-$(( width - 2 ))s${{colour}}║${{NC}}\\n" "Full command: git $*" >&2
    printf "${{colour}}╚%${{width}}s╝${{NC}}\\n" "" | tr ' ' '═' >&2
    echo "" >&2

    if ! [ -t 0 ] && ! [ -e /dev/tty ]; then
        echo -e "${{RED}}✗ Git Guardian: no TTY — blocking action (safety default)${{NC}}" >&2
        log "BLOCKED (no TTY): $risk_level — $description"
        return 1
    fi

    read -p "$(echo -e "${{colour}}Allow this? [y/N]: ${{NC}}")" answer < /dev/tty
    case "$answer" in
        [yY]|[yY][eE][sS])
            log "ALLOWED (user approved): $risk_level — $description"
            return 0
            ;;
        *)
            echo -e "${{RED}}✗ Blocked by Git Guardian${{NC}}" >&2
            log "BLOCKED (user denied): $risk_level — $description"
            return 1
            ;;
    esac
}}

# ─── Detect the subcommand (skip global flags) ───
subcommand=""
sub_args=()
skip_next=false
for arg in "$@"; do
    if $skip_next; then
        skip_next=false
        continue
    fi
    if [[ -z "$subcommand" ]]; then
        case "$arg" in
            -C|-c|--git-dir|--work-tree|--namespace) skip_next=true; continue ;;
            -*) continue ;;
            *)  subcommand="$arg" ;;
        esac
    else
        sub_args+=("$arg")
    fi
done

# ─── Rules ───
case "$subcommand" in

    push)
        if args_match '^(--force|-f)$' "${{sub_args[@]}}"; then
            confirm "HIGH" "Force push detected. This rewrites remote history." "$@" || exit 1
        elif args_match '^--force-with-lease' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Force-with-lease push. Safer, but still rewrites history." "$@" || exit 1
        elif args_match '^(--delete|-d)$' "${{sub_args[@]}}" || args_match '^:.' "${{sub_args[@]}}"; then
            confirm "HIGH" "Remote branch deletion detected." "$@" || exit 1
        elif has_protected_branch "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Push to a protected branch name detected." "$@" || exit 1
{push_extra}{push_else}
        fi
        ;;

    branch)
        if args_match '^(-d|-D|--delete)$' "${{sub_args[@]}}"; then
            if has_protected_branch "${{sub_args[@]}}"; then
                echo -e "${{RED}}✗ Git Guardian: BLOCKED — deleting a protected branch is not allowed${{NC}}" >&2
                log "HARD-BLOCKED: branch delete on protected branch — git $*"
                exit 1
            elif args_match '^-D$' "${{sub_args[@]}}"; then
                confirm "MEDIUM" "Force-deleting a local branch." "$@" || exit 1
            fi
        fi
        ;;

    reset)
        if args_match '^--hard$' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Hard reset. Uncommitted changes will be lost." "$@" || exit 1
        fi
        ;;

    clean)
        if args_match '^(-f|--force)$' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Forced clean. Untracked files will be deleted." "$@" || exit 1
        fi
        ;;

    rebase)
        if args_match '^--onto$' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Rebase --onto detected. This rewrites commit history." "$@" || exit 1
        elif args_match '^(-i|--interactive)$' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Interactive rebase. This rewrites commit history." "$@" || exit 1
        fi
        ;;

    commit)
        if args_match '^--amend$' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Amending the last commit. Risky if already pushed." "$@" || exit 1
        fi
        ;;

    checkout)
        if has_protected_branch "${{sub_args[@]}}"; then
            echo -e "${{CYAN}}● Git Guardian: switching to a primary branch${{NC}}" >&2
            log "INFO: checkout to primary branch"
        elif args_match '^--$' "${{sub_args[@]}}" || [[ "${{sub_args[0]}}" == "." ]]; then
            confirm "MEDIUM" "Discarding uncommitted changes to working tree." "$@" || exit 1
        fi
        ;;

    switch)
        if has_protected_branch "${{sub_args[@]}}"; then
            echo -e "${{CYAN}}● Git Guardian: switching to a primary branch${{NC}}" >&2
            log "INFO: switch to primary branch"
        fi
        ;;

    restore)
        if args_match '^\\.$' "${{sub_args[@]}}"; then
            confirm "MEDIUM" "Restoring all files. Uncommitted changes may be lost." "$@" || exit 1
        fi
        ;;

    stash)
        if [[ "${{sub_args[0]}}" == "drop" ]]; then
            confirm "MEDIUM" "Dropping a stash entry. This cannot be undone easily." "$@" || exit 1
        elif [[ "${{sub_args[0]}}" == "clear" ]]; then
            confirm "HIGH" "Clearing ALL stashes. This cannot be undone." "$@" || exit 1
        fi
        ;;

esac

exec "$REAL_GIT" "$@"
''')


def generate_dockerfile(config: SetupConfig) -> str:
    sections = []

    # Base
    sections.append(textwrap.dedent("""\
        FROM node:20-bookworm-slim

        # ============================================================
        # 1. System dependencies
        # ============================================================
        RUN apt-get update && apt-get install -y --no-install-recommends \\
            git curl wget sudo ca-certificates gnupg openssh-client zip unzip \\
            build-essential pkg-config \\
            ripgrep fd-find jq tree htop \\
            python3 python3-pip python3-venv python3-dev \\"""))

    if config.include_db_clients:
        sections.append("""\
    sqlite3 libsqlite3-dev postgresql-client default-mysql-client redis-tools \\""")

    # Close the apt-get and add fd-find symlink
    sections.append("""\
    && rm -rf /var/lib/apt/lists/* \\
    && ln -s "$(which fdfind)" /usr/local/bin/fd \\
    && ln -sf /usr/bin/python3 /usr/bin/python""")

    # GitHub CLI
    if config.include_github_cli:
        sections.append(textwrap.dedent("""
        # ============================================================
        # 2. GitHub CLI
        # ============================================================
        RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \\
                | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \\
            && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \\
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \\
                | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \\
            && apt-get update && apt-get install -y gh \\
            && rm -rf /var/lib/apt/lists/*"""))

    # Docker CLI
    if config.include_docker_cli:
        sections.append(textwrap.dedent("""
        # ============================================================
        # 3. Docker CLI
        # ============================================================
        RUN curl -fsSL https://download.docker.com/linux/debian/gpg \\
                | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \\
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable" \\
                | tee /etc/apt/sources.list.d/docker.list > /dev/null \\
            && apt-get update && apt-get install -y docker-ce-cli \\
            && rm -rf /var/lib/apt/lists/*"""))

    # Cloud CLIs
    if config.include_cloud_clis:
        sections.append(textwrap.dedent("""
        # ============================================================
        # 4. Cloud CLIs — AWS, GCP, Azure
        # ============================================================
        RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o "awscliv2.zip" \\
            && unzip -q awscliv2.zip && ./aws/install && rm -rf aws awscliv2.zip

        RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \\
                | tee /etc/apt/sources.list.d/google-cloud-sdk.list \\
            && curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg \\
                | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \\
            && apt-get update && apt-get install -y --no-install-recommends google-cloud-cli \\
            && rm -rf /var/lib/apt/lists/*

        RUN curl -fsSL https://aka.ms/InstallAzureCLIDeb | bash"""))

    # Infrastructure
    if config.include_infra_tools:
        sections.append(textwrap.dedent("""
        # ============================================================
        # 5. Infrastructure — Terraform + kubectl
        # ============================================================
        RUN curl -fsSL https://apt.releases.hashicorp.com/gpg \\
                | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \\
            && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main" \\
                | tee /etc/apt/sources.list.d/hashicorp.list \\
            && apt-get update && apt-get install -y terraform \\
            && rm -rf /var/lib/apt/lists/*

        RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key \\
                | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg \\
            && echo "deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" \\
                | tee /etc/apt/sources.list.d/kubernetes.list \\
            && apt-get update && apt-get install -y kubectl \\
            && rm -rf /var/lib/apt/lists/*"""))

    # Node package managers + Claude Code
    sections.append(textwrap.dedent("""
        # ============================================================
        # 6. Node.js package managers + Claude Code
        # ============================================================
        RUN npm install -g pnpm
        RUN npm install -g @anthropic-ai/claude-code \\
            && npm cache clean --force"""))

    # ML packages
    if config.include_ml_packages:
        sections.append(textwrap.dedent("""
        # ============================================================
        # 7. Python ML/Data Science packages (CPU-only)
        # ============================================================
        RUN pip install --break-system-packages --no-cache-dir \\
            torch --index-url https://download.pytorch.org/whl/cpu \\
            && pip install --break-system-packages --no-cache-dir \\
            numpy pandas scipy scikit-learn matplotlib jupyter notebook ipykernel"""))

    # User setup
    sections.append(textwrap.dedent("""
        # ============================================================
        # User setup
        # ============================================================
        ARG USER_UID=1000
        ARG USER_GID=1000
        # Handle UID/GID conflicts (e.g. macOS GID 20 already exists as dialout in Debian)
        RUN if ! getent group "$USER_GID" >/dev/null 2>&1; then \
              groupmod --gid "$USER_GID" node; \
            elif [ "$(getent group "$USER_GID" | cut -d: -f1)" = "node" ]; then \
              true; \
            fi \
            && usermod --uid "$USER_UID" --gid "$USER_GID" node \
            && chown -R "$USER_UID":"$USER_GID" /home/node

        # Minimal sudo: only credential helper operations (no apt-get, chmod, chown)
        RUN echo "node ALL=(ALL) NOPASSWD: /usr/bin/tee /root/.git-credentials, /bin/cat /root/.git-credentials, /usr/bin/cat /root/.git-credentials, /bin/chmod 600 /root/.git-credentials, /usr/bin/chmod 600 /root/.git-credentials" >> /etc/sudoers

        RUN git config --system push.default current \\
            && git config --system push.autoSetupRemote true

        # ── Git Guardian wrapper ──
        COPY git-guardian.sh /usr/local/bin/git
        RUN chmod +x /usr/local/bin/git"""))

    # Workdir + user switch
    sections.append(textwrap.dedent("""
        # Disable Claude Code auto-update — pinned at build time, avoids
        # permission errors when running as non-root 'node' user
        ENV DISABLE_AUTOUPDATER=1

        WORKDIR /workspace
        USER node"""))

    sections.append("""
        CMD ["bash"]""")

    return "\n".join(sections)


def generate_run_script(config: SetupConfig) -> str:
    all_ports = config.ports + [int(p) for p in config.custom_ports if p.isdigit()]
    ports_array = " ".join(str(p) for p in all_ports)

    # Build docker run flags — ports are now dynamic via ${PORT_ARGS[@]}
    docker_flags = []
    docker_flags.append('    --name "$CONTAINER_NAME"')
    docker_flags.append('    --network "$NETWORK_MODE"')
    docker_flags.append('    "${PORT_ARGS[@]}"')
    docker_flags.append('    "${PORT_ENV_ARGS[@]}"')
    docker_flags.append('    --cap-drop ALL')
    # Minimal capabilities — DAC_OVERRIDE and SYS_PTRACE removed (not needed for Claude Code)
    for cap in ['AUDIT_WRITE', 'CHOWN', 'FOWNER', 'FSETID',
                'KILL', 'NET_BIND_SERVICE', 'SETGID', 'SETUID']:
        docker_flags.append(f'    --cap-add {cap}')
    if config.enable_resource_limits:
        docker_flags.append(f'    --memory {config.resource_memory}')
        docker_flags.append(f'    --cpus {config.resource_cpus}')
    docker_flags.append('    -v "$PROJECT_DIR:/workspace"')
    docker_flags.append('    -v "$HOME/.claude:/home/node/.claude"')
    docker_flags.append('    -v "$HOME/.claude.json:/home/node/.claude.json"')
    if config.enable_readonly_hooks:
        docker_flags.append('    -v "$PROJECT_DIR/.claude/hooks:/workspace/.claude/hooks:ro"')
    docker_flags.append('    --env-file "$ENV_FILE"')
    docker_flags.append('    -e "HOST_GIT_NAME=$HOST_GIT_NAME"')
    docker_flags.append('    -e "HOST_GIT_EMAIL=$HOST_GIT_EMAIL"')
    docker_flags.append('    -e DISABLE_AUTOUPDATER=1')
    docker_flags.append('    alcatraz:latest')

    docker_flags_str = " \\\n".join(docker_flags)

    timeout_prefix = ""
    if config.enable_session_timeout:
        timeout_prefix = f"timeout {config.session_timeout_hours}h "

    api_key_block = ""
    if config.auth_method == "api_key":
        api_key_block = """
# ── Anthropic API key ──
ANTHROPIC_API_KEY_FILE="$HOME/.alcatraz-anthropic-key"
if [ -f "$ANTHROPIC_API_KEY_FILE" ]; then
    ANTHROPIC_KEY=$(cat "$ANTHROPIC_API_KEY_FILE" | tr -d '[:space:]')
    if echo "$ANTHROPIC_KEY" | grep -qE '^sk-ant-[a-zA-Z0-9_-]+$'; then
        printf 'ANTHROPIC_API_KEY=%s\\n' "$ANTHROPIC_KEY" >> "$ENV_FILE"
    else
        echo "WARNING: Invalid Anthropic API key format in $ANTHROPIC_API_KEY_FILE — skipping"
    fi
fi
"""

    return textwrap.dedent(f'''\
#!/bin/bash
set -e
# run.sh — Launch Alcatraz
# Generated by Alcatraz Setup Wizard v{VERSION}

# Usage:
#   ./run.sh                                         # Current dir, deterministic ports (default)
#   ./run.sh /path/to/project                        # Specific dir, deterministic ports
#   ./run.sh fixed                                   # Current dir, fixed 1:1 ports (3000:3000 etc.)
#   ./run.sh none                                    # Current dir, offline (no network)
#   ./run.sh /path/to/project noports                # Specific dir, no port forwarding
#   ./run.sh none noports                            # Offline + no ports
#
# Port modes (order-independent, mix with any other args):
#   (default)  — Deterministic hash-based ports, parallel safe
#   fixed      — 1:1 mapping (3000:3000), only one container at a time
#   noports    — No port forwarding at all

# --- Configuration ---
GITHUB_TOKEN_FILE="$HOME/.alcatraz-token"
CONTAINER_PORTS=({ports_array})  # Container-side ports to forward

# --- Parse arguments ---
# Accepts args in any order: a directory path, a network mode (none/bridge),
# and a port mode (fixed/noports). Unrecognised args are treated as the project dir.
# Default: {config.port_mode} ports + {config.default_network} network + current directory.
PROJECT_DIR="."
NETWORK_MODE="{config.default_network}"
PORT_MODE="{config.port_mode}"

for arg in "$@"; do
    case "$arg" in
        fixed)       PORT_MODE="fixed" ;;
        noports)     PORT_MODE="noports" ;;
        none)        NETWORK_MODE="none" ;;
        bridge)      NETWORK_MODE="bridge" ;;
        *)           PROJECT_DIR="$arg" ;;
    esac
done

# --- Validate project directory ---
if [ ! -d "$PROJECT_DIR" ]; then
    echo "Error: Directory '$PROJECT_DIR' does not exist."
    exit 1
fi

PROJECT_DIR=$(cd "$PROJECT_DIR" && pwd)
PROJECT_NAME=$(basename "$PROJECT_DIR")

# --- Read the GitHub token ---
# Instead of passing the token as an environment variable (where Claude can read it
# via `echo $GITHUB_TOKEN`, `env`, or `cat /proc/self/environ`), we write it to a
# root-owned credential file inside the container. The git credential helper reads
# from this file, but the `node` user cannot access it directly. This prevents
# Claude from extracting the raw token and using it with curl/wget to bypass the
# Git Guardian via the GitHub API.
if [ ! -f "$GITHUB_TOKEN_FILE" ]; then
    echo "Error: Store your GitHub PAT in $GITHUB_TOKEN_FILE"
    echo "  echo 'github_pat_xxxx' > $GITHUB_TOKEN_FILE && chmod 600 $GITHUB_TOKEN_FILE"
    exit 1
fi

GITHUB_TOKEN=$(cat "$GITHUB_TOKEN_FILE")

# Warn if token file has loose permissions
TOKEN_PERMS=$(stat -c '%a' "$GITHUB_TOKEN_FILE" 2>/dev/null || stat -f '%Lp' "$GITHUB_TOKEN_FILE" 2>/dev/null)
if [ -n "$TOKEN_PERMS" ] && [ "$TOKEN_PERMS" != "600" ] && [ "$TOKEN_PERMS" != "400" ]; then
    echo "WARNING: $GITHUB_TOKEN_FILE has permissions $TOKEN_PERMS (should be 600)"
    echo "  Fix: chmod 600 $GITHUB_TOKEN_FILE"
fi

# Claude Code authentication: handled by the volume mount -v "$HOME/.claude:/home/node/.claude"
# which makes ~/.claude/.credentials.json visible inside the container. Claude Code reads
# this file natively — no environment variable needed. Do NOT set CLAUDE_CODE_OAUTH_TOKEN:
# it overrides .credentials.json and breaks auth if the value is stale or malformed.

# --- Temp env file for non-sensitive vars only ---
ENV_FILE=$(mktemp)
chmod 600 "$ENV_FILE"
{api_key_block}
trap 'rm -f "$ENV_FILE"' EXIT

# --- Token expiry reminder ---
EXPIRY_FILE="$HOME/.alcatraz-token-expiry"
if [ -f "$EXPIRY_FILE" ]; then
    EXPIRY_DATE=$(cat "$EXPIRY_FILE")
    # macOS uses -j -f, Linux/WSL uses -d
    if date -j -f "%Y-%m-%d" "$EXPIRY_DATE" +%s > /dev/null 2>&1; then
        EXPIRY_TS=$(date -j -f "%Y-%m-%d" "$EXPIRY_DATE" +%s)
    else
        EXPIRY_TS=$(date -d "$EXPIRY_DATE" +%s 2>/dev/null || echo 0)
    fi
    NOW_TS=$(date +%s)
    if [ "$EXPIRY_TS" -gt 0 ]; then
        DAYS_LEFT=$(( (EXPIRY_TS - NOW_TS) / 86400 ))
        if [ "$DAYS_LEFT" -le 0 ]; then
            echo "GitHub PAT expired on $EXPIRY_DATE! Generate a new one:"
            echo "  1. Create a new token on GitHub"
            echo "  2. echo 'github_pat_xxxx' > ~/.alcatraz-token"
            echo "  3. echo 'YYYY-MM-DD' > ~/.alcatraz-token-expiry"
            exit 1
        elif [ "$DAYS_LEFT" -le 7 ]; then
            echo "WARNING: GitHub PAT expires in $DAYS_LEFT day(s) ($EXPIRY_DATE) -- rotate soon"
        fi
    fi
fi

# --- Read host git identity (fallback for inside the container) ---
HOST_GIT_NAME=$(git config user.name 2>/dev/null || echo "")
HOST_GIT_EMAIL=$(git config user.email 2>/dev/null || echo "")

# --- Ensure .claude.json exists as a file (not a directory) ---
if [ ! -f "$HOME/.claude.json" ]; then
    # Remove if Docker previously created it as a directory
    rm -rf "$HOME/.claude.json" 2>/dev/null
    echo '{{"hasCompletedOnboarding":true}}' > "$HOME/.claude.json"
fi

# --- Build port mapping arguments ---
PORT_ARGS=()
PORT_ENV_ARGS=()
CONTAINER_NAME="alcatraz-${{PROJECT_NAME}}-$$"

case "$PORT_MODE" in
    noports)
        # No port forwarding at all
        ;;
    fixed)
        # 1:1 mapping — only works for a single container
        for cport in "${{CONTAINER_PORTS[@]}}"; do
            PORT_ARGS+=(-p "127.0.0.1:${{cport}}:${{cport}}")
            PORT_ENV_ARGS+=(-e "HOST_PORT_${{cport}}=${{cport}}")
        done
        ;;
    *)
        # Deterministic: hash project name → stable base port in range 10000-59996
        # Multiply by 4 so each project gets a non-overlapping block of consecutive ports
        HASH=$(echo -n "$PROJECT_NAME" | cksum | awk '{{print $1}}')
        BASE_PORT=$(( (HASH % 12500) * ${{#CONTAINER_PORTS[@]}} + 10000 ))

        # Collision check: if base port is in use, offset by PID to find a free block
        if command -v ss &>/dev/null; then
            CHECK_CMD="ss -tlnH"
        elif command -v netstat &>/dev/null; then
            CHECK_CMD="netstat -tln"
        else
            CHECK_CMD=""
        fi

        if [ -n "$CHECK_CMD" ] && $CHECK_CMD 2>/dev/null | grep -q ":${{BASE_PORT}} "; then
            BASE_PORT=$(( BASE_PORT + ($$ % 5000) * ${{#CONTAINER_PORTS[@]}} ))
            # Wrap around if we exceed the safe range
            if [ "$BASE_PORT" -gt 59996 ]; then
                BASE_PORT=$(( (BASE_PORT % 50000) + 10000 ))
            fi
        fi

        OFFSET=0
        for cport in "${{CONTAINER_PORTS[@]}}"; do
            HPORT=$((BASE_PORT + OFFSET))
            PORT_ARGS+=(-p "127.0.0.1:${{HPORT}}:${{cport}}")
            PORT_ENV_ARGS+=(-e "HOST_PORT_${{cport}}=${{HPORT}}")
            OFFSET=$((OFFSET + 1))
        done
        ;;
esac

echo -e "\\033[1;36m════════════════════════════════════════════════════════════════════\\033[0m"
echo -e "\\033[1;36m █████╗ ██╗      ██████╗ █████╗ ████████╗██████╗  █████╗ ███████╗\\033[0m"
echo -e "\\033[1;36m██╔══██╗██║     ██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚══███╔╝\\033[0m"
echo -e "\\033[1;36m███████║██║     ██║     ███████║   ██║   ██████╔╝███████║  ███╔╝ \\033[0m"
echo -e "\\033[1;36m██╔══██║██║     ██║     ██╔══██║   ██║   ██╔══██╗██╔══██║ ███╔╝  \\033[0m"
echo -e "\\033[1;36m██║  ██║███████╗╚██████╗██║  ██║   ██║   ██║  ██║██║  ██║███████╗\\033[0m"
echo -e "\\033[1;36m╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝\\033[0m"
echo ""
echo "Project:  $PROJECT_NAME"
echo "Path:     $PROJECT_DIR"
echo "Network:  $NETWORK_MODE"

if [ "$PORT_MODE" = "noports" ]; then
    echo "Ports:    None (no port forwarding)"
elif [ "$PORT_MODE" = "fixed" ]; then
    echo "Ports:    ${{CONTAINER_PORTS[*]}} → localhost (1:1 fixed)"
else
    echo "Ports:"
    OFFSET=0
    for cport in "${{CONTAINER_PORTS[@]}}"; do
        HPORT=$((BASE_PORT + OFFSET))
        echo "          ${{cport}} → localhost:${{HPORT}}"
        OFFSET=$((OFFSET + 1))
    done
fi

echo -e "\\033[1;36m════════════════════════════════════════════════════════════════════\\033[0m"

# --- Optional volume mounts ---
# Uncomment and add these to the docker run command below as needed:
#   -v /var/run/docker.sock:/var/run/docker.sock       # Docker-in-Docker
#       ⚠ WARNING: Mounting the Docker socket grants FULL HOST ROOT ACCESS.
#       Any process in the container can create privileged containers, read
#       host files, and escape the sandbox entirely. Only enable this if you
#       understand the security implications.
#   -v "$HOME/.aws:/home/node/.aws:ro"                 # AWS credentials
#   -v "$HOME/.config/gcloud:/home/node/.config/gcloud:ro"  # GCP credentials
#   -v "$HOME/.azure:/home/node/.azure:ro"             # Azure credentials
#   -v "$HOME/.kube:/home/node/.kube:ro"               # Kubernetes config
#   -v "$HOME/.ssh:/home/node/.ssh:ro"                 # SSH keys

docker run -it --rm \\
{docker_flags_str} \\
    bash -c "
        # Ensure onboarding is marked complete (prevents setup wizard on every launch)
        if [ ! -f /home/node/.claude.json ] || ! grep -q \\"hasCompletedOnboarding\\" /home/node/.claude.json 2>/dev/null; then
            echo '{{\\"hasCompletedOnboarding\\":true}}' > /home/node/.claude.json
        fi

        # Write the GitHub token to a root-owned file that only root can read.
        # The git credential helper reads from this file, but the node user (Claude)
        # cannot access it directly — preventing token extraction via env, printenv,
        # or /proc/self/environ.
        # Uses here-string (<<<) instead of echo to avoid exposing the token in ps output.
        sudo tee /root/.git-credentials > /dev/null <<< '${{GITHUB_TOKEN}}'
        sudo chmod 600 /root/.git-credentials

        # Configure git to use a credential helper that reads the root-owned token.
        # The helper runs via sudo so it can read /root/.git-credentials, but the
        # token value never appears in the node user's environment or shell history.
        /usr/bin/git config --global credential.helper '!f() {{ echo \\"username=x-access-token\\"; echo \\"password=\\$(sudo cat /root/.git-credentials)\\"; }}; f'

        # Use the host git identity, falling back to the last commit author, then a safe default.
        GIT_NAME=\\"\\${{HOST_GIT_NAME:-\\$(/usr/bin/git -C /workspace log -1 --format=%an 2>/dev/null || echo Claude)}}\\"
        GIT_EMAIL=\\"\\${{HOST_GIT_EMAIL:-\\$(/usr/bin/git -C /workspace log -1 --format=%ae 2>/dev/null || echo claude@local)}}\\"
        /usr/bin/git config --global user.name \\"\\$GIT_NAME\\"
        /usr/bin/git config --global user.email \\"\\$GIT_EMAIL\\"

        # Build port mapping context for Claude so it tells users the correct host URLs
        PORT_CONTEXT=''
        for var in \\$(env | grep ^HOST_PORT_ | sort); do
            CPORT=\\$(echo \\"\\$var\\" | sed 's/HOST_PORT_//;s/=.*//')
            HPORT=\\$(echo \\"\\$var\\" | sed 's/.*=//')
            PORT_CONTEXT=\\"\\${{PORT_CONTEXT}}  container port \\$CPORT → host localhost:\\$HPORT
\\"
        done
        if [ -n \\"\\$PORT_CONTEXT\\" ]; then
            PORT_PROMPT=\\"You are running inside a Docker container. Container ports are mapped to the host as follows:
\\${{PORT_CONTEXT}}
When the user starts a dev server or asks to view a URL, ALWAYS tell them the HOST port from the mappings above (e.g., for port 3000 use localhost:\\$(env | grep ^HOST_PORT_3000= | cut -d= -f2)), NEVER the container-internal port.\\"
        else
            PORT_PROMPT=\\"You are running inside a Docker container with no port forwarding. Dev servers started here won't be accessible from the host browser.\\"
        fi

        # --dangerously-skip-permissions is intentional here: the Docker container
        # itself is the sandbox, and git-guardian.sh handles git-specific safety.
        {timeout_prefix}claude --dangerously-skip-permissions --append-system-prompt \\"\\$PORT_PROMPT\\"
    "
''')


def generate_pretool_hook(config: SetupConfig) -> str:
    branches_re = '|'.join(config.protected_branches)
    return textwrap.dedent(f'''\
#!/bin/bash
# pretool-hook.sh — PreToolUse hook that blocks dangerous commands
# Generated by Alcatraz Setup Wizard v{VERSION}
# Exit code 0 = allow, exit code 2 = block

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

if [ "$TOOL_NAME" != "Bash" ] || [ -z "$COMMAND" ]; then
    exit 0
fi

BLOCKED_PATTERNS=(
    'git push.*--force'
    'git push.*-f\\b'
    'git push.*--delete'
    'git push.*:refs/'
    'git stash clear'
    # Block deletion of protected branches (main, master, etc.)
    'git branch.*(-[dD]|--delete).*\\b({branches_re})\\b'
    'gh repo delete'
    'gh api.*/repos.*DELETE'
    'curl.*api\\.github\\.com'
    'wget.*api\\.github\\.com'
    'rm -rf /'
    'rm -rf ~'
    'rm -rf /home'
    'rm -rf /workspace'
    'chmod 777'
    # Block ANY direct reference to .git-credentials — catches sudo cat,
    # sudo /bin/cat, sudo /usr/bin/cat, head, tee overwrite, etc.
    # Safe because the credential helper runs inside git (not via Bash tool).
    '\\.git-credentials'
    # Prevent bypassing Git Guardian via sudo or direct binary path
    'sudo.*/usr/bin/git'
    'sudo.*git push'
    # Prevent reconfiguring the credential helper to extract the token
    'git config.*credential\\.helper'
    # Prevent command obfuscation to bypass pattern checks
    'base64.*-[dD].*\\|.*bash'
    'base64.*--decode.*\\|.*sh'
    'base64.*-[dD].*\\|.*eval'
    # Prevent env inspection for token extraction
    '/proc/.*environ'
)

for pattern in "${{BLOCKED_PATTERNS[@]}}"; do
    if echo "$COMMAND" | grep -qE "$pattern"; then
        echo "BLOCKED by PreToolUse hook: matches '$pattern'" >&2
        echo "Command was: $COMMAND" >&2
        exit 2
    fi
done

exit 0
''')


def generate_settings_json(config: SetupConfig) -> str:
    settings = {}

    if config.enable_deny_list:
        deny = [
            "Bash(gh repo delete*)",
            "Bash(gh api */repos*DELETE*)",
            "Bash(curl*api.github.com*)",
            "Bash(wget*api.github.com*)",
            "Bash(rm -rf /*)",
            "Bash(rm -rf ~*)",
            "Bash(chmod 777*)",
            "Bash(git push*--force*)",
            "Bash(git push*--delete*)",
            "Bash(git stash clear*)",
        ]
        # Block deletion of protected branches
        for branch in config.protected_branches:
            deny.append(f"Bash(git branch*-d *{branch}*)")
            deny.append(f"Bash(git branch*-D *{branch}*)")
            deny.append(f"Bash(git branch*--delete *{branch}*)")
        settings["permissions"] = {"deny": deny}

    if config.enable_pretool_hook:
        settings["hooks"] = {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": "/workspace/.claude/hooks/pretool-hook.sh"
                        }
                    ]
                }
            ]
        }

    return json.dumps(settings, indent=2)


def generate_branch_ruleset() -> str:
    """Return the recommended GitHub branch ruleset JSON for import.

    This ruleset protects the default branch with the same rules shown in the
    Branch Protection wizard step: no deletions, no force-pushes, and pull
    requests required with zero approvals (solo-friendly default).  Users
    import this file directly via Settings → Rules → Rulesets → New →
    Import a ruleset.  Teams should increase required approvals to 1+.
    """
    ruleset = {
        "name": "main",
        "target": "branch",
        "enforcement": "active",
        "conditions": {
            "ref_name": {
                "exclude": [],
                "include": ["~DEFAULT_BRANCH"],
            }
        },
        "rules": [
            {"type": "deletion"},
            {"type": "non_fast_forward"},
            {
                "type": "pull_request",
                "parameters": {
                    "required_approving_review_count": 0,
                    "dismiss_stale_reviews_on_push": True,
                    "required_reviewers": [],
                    "require_code_owner_review": False,
                    "require_last_push_approval": False,
                    "required_review_thread_resolution": False,
                    "allowed_merge_methods": ["merge", "squash", "rebase"],
                },
            },
        ],
        "bypass_actors": [],
    }
    return json.dumps(ruleset, indent=2)


def generate_wrapper_script(config: SetupConfig) -> str:
    """Generate the `alcatraz` launcher wrapper that can be placed on PATH."""
    return textwrap.dedent(f'''\
#!/bin/bash
# alcatraz — Quick launcher for Alcatraz Docker environment
# Generated by Alcatraz Setup Wizard v{VERSION}
#
# Usage:
#   alcatraz                          # Current dir, default settings
#   alcatraz /path/to/project         # Specific project
#   alcatraz . fixed                  # Fixed ports
#   alcatraz none                     # Offline mode
#   alcatraz /path/to/project none noports
#
# All arguments are forwarded directly to run.sh.
# Install to PATH:  ln -sf {config.install_dir}/alcatraz ~/.local/bin/alcatraz

INSTALL_DIR="{config.install_dir}"
RUN_SCRIPT="$INSTALL_DIR/run.sh"

if [ ! -f "$RUN_SCRIPT" ]; then
    echo "Error: Alcatraz not found at $INSTALL_DIR"
    echo ""
    echo "Either the installation was moved or not yet completed."
    echo "Re-run the setup wizard or update the INSTALL_DIR in this script."
    exit 1
fi

exec "$RUN_SCRIPT" "$@"
''')


def _generate_files(config: SetupConfig):
    """Generate all configuration files to install_dir.

    Used by step_review_and_generate (custom mode) and
    _recommended_generate_and_build (recommended mode).
    """
    install_dir = Path(config.install_dir)
    install_dir.mkdir(parents=True, exist_ok=True)

    def make_executable(path: Path):
        """chmod +x, ignoring errors on filesystems that don't support it (e.g. NTFS via WSL)."""
        try:
            path.chmod(0o755)
        except OSError:
            pass

    def write_lf(path: Path, content: str):
        """Write file with Unix (LF) line endings — required for bash scripts on WSL."""
        path.write_text(content, newline="\n")

    # Calculate actual file count for accurate progress
    file_count = 7  # Dockerfile, git-guardian.sh, run.sh, alcatraz, build.sh, branch-ruleset.json, auth.sh
    if config.enable_pretool_hook:
        file_count += 1
    if config.enable_deny_list or config.enable_pretool_hook:
        file_count += 1

    try:
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            console=console,
        ) as progress:
            task = progress.add_task("Generating files...", total=file_count)

            # Dockerfile
            write_lf(install_dir / "Dockerfile", generate_dockerfile(config))
            progress.update(task, advance=1, description="Wrote Dockerfile")

            # Git Guardian
            guardian_path = install_dir / "git-guardian.sh"
            write_lf(guardian_path, generate_git_guardian(config))
            make_executable(guardian_path)
            progress.update(task, advance=1, description="Wrote git-guardian.sh")

            # run.sh
            run_path = install_dir / "run.sh"
            write_lf(run_path, generate_run_script(config))
            make_executable(run_path)
            progress.update(task, advance=1, description="Wrote run.sh")

            # alcatraz launcher wrapper
            wrapper_path = install_dir / "alcatraz"
            write_lf(wrapper_path, generate_wrapper_script(config))
            make_executable(wrapper_path)
            progress.update(task, advance=1, description="Wrote alcatraz")

            # PreToolUse hook
            if config.enable_pretool_hook:
                hook_path = install_dir / "pretool-hook.sh"
                write_lf(hook_path, generate_pretool_hook(config))
                make_executable(hook_path)
                progress.update(task, advance=1, description="Wrote pretool-hook.sh")

            # settings.json
            if config.enable_deny_list or config.enable_pretool_hook:
                write_lf(install_dir / "settings.json", generate_settings_json(config))
                progress.update(task, advance=1, description="Wrote settings.json")

            # branch-ruleset.json
            write_lf(install_dir / "branch-ruleset.json", generate_branch_ruleset())
            progress.update(task, advance=1, description="Wrote branch-ruleset.json")

            # build.sh
            build_script = textwrap.dedent(f"""\
#!/bin/bash
set -e
# build.sh — Build the Alcatraz Docker image
# Generated by Alcatraz Setup Wizard v{VERSION}

echo "Building Alcatraz Docker image..."
echo "This may take 10-15 minutes on first build."
echo ""

cd "$(dirname "$0")"

docker build -t alcatraz:latest \\
  --build-arg USER_UID=$(id -u) \\
  --build-arg USER_GID=$(id -g) .

echo ""
echo "Image built successfully!"
echo ""
echo "Launch on a project:"
echo "  alcatraz /path/to/project"
""")
            build_path = install_dir / "build.sh"
            write_lf(build_path, build_script)
            make_executable(build_path)
            progress.update(task, advance=1, description="Wrote build.sh")

            # auth.sh
            auth_script = textwrap.dedent(f"""\
#!/bin/bash
set -e
# auth.sh — One-time OAuth login for Claude Code
# Generated by Alcatraz Setup Wizard v{VERSION}

echo "Setting up Claude Code authentication..."

# Ensure credential paths exist on host
if [ -d "$HOME/.claude.json" ]; then
  echo "Warning: $HOME/.claude.json is a directory — removing it"
  rm -rf "$HOME/.claude.json"
fi
if [ ! -f "$HOME/.claude.json" ]; then
  echo '{{"hasCompletedOnboarding":true}}' > "$HOME/.claude.json"
fi
mkdir -p "$HOME/.claude"

echo ""
echo "Launching auth container — a browser window will open."
echo "Complete the login, then type /exit in the terminal."
echo ""

docker run -it --rm \\
  -v "$HOME/.claude:/home/node/.claude" \\
  -v "$HOME/.claude.json:/home/node/.claude.json" \\
  alcatraz:latest \\
  claude --dangerously-skip-permissions
""")
            auth_path = install_dir / "auth.sh"
            write_lf(auth_path, auth_script)
            make_executable(auth_path)
            progress.update(task, advance=1, description="Wrote auth.sh")

    except Exception as e:
        console.print()
        console.print(f"  [red bold]x Error generating files:[/] [red]{e}[/]")
        console.print(f"  [dim]Directory: {install_dir}[/]")
        console.print()
        import traceback
        console.print(f"  [dim]{traceback.format_exc()}[/]")
        sys.exit(1)

    # ── Brief success ──
    console.print()
    console.print(f"  [bold green]✓[/] All files generated in [cyan]{config.install_dir}[/]")
    console.print()
